model:
  name: 'resnet50_fc512'
  pretrained: True

data:
  type: 'image'
  sources: ['motsynth_split_1_mini']
  targets: ['mot17']
  height: 256
  width: 128
  combineall: False
  transforms: ['random_flip']
  save_dir: 'resnet50_fc512_motsynth_train'

loss:
  name: 'softmax'
  softmax:
    label_smooth: True

train:
  optim: 'amsgrad'
  lr: 0.0009
  max_epoch: 19
  batch_size: 180
  fixbase_epoch: 5
  open_layers: ['fc', 'classifier']
  lr_scheduler: 'single_step'
  stepsize: [15]

test:
  batch_size: 224
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: 1
  rerank: False
  start_eval: 1